.devcontainer/default/devcontainer.json
.devcontainer/withenvfile/devcontainer.json
README.md
go.mod

chore: Update Go Version

---

DEVELOPER.md
assets/provider-config-local.txt
docs/index.md
docs/resources/app.md
docs/resources/org_quota.md
examples/provider/provider.tf
examples/resources/cloudfoundry_app/resource.tf
examples/resources/cloudfoundry_org_quota/resource.tf
internal/provider/fixtures/resource_mta_invalid_mta_path.yaml
main.go
migration-guide/Readme.md

- Update reference to `cloudfoundry/cloudfoundry`

chore: Update references

---

.lycheeignore

- closes #10 
- Add links to exclusion list that cannot be checked by GH Action for checking link validity
- Execute GH Action for Link checks
- GH Action gets executed successfully and excludes the links as defined in the `.lycheeignore` file
n/a

fix: ignore list for link checker

---

.github/workflows/test.yml

- fix #19 
```bash
go test ./...
```
```
...
```
- ...

Add terraform 1.9 for acceptance tests

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

chore: Prep v1.0.0-rc2

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

- 🚀 Lift-off! GA release ready – the first of many adventures. 
- 🌌 Try it, love it, more magic on the way!

chore: Prep Release v1.0.0

---

docs/index.md
internal/provider/provider.go

- fixes #54 
```bash
go test ./...
```
```
...
```
- ...

Change sensitivity of provider attributes

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

chore: Prep Work release 1.1.0

---

docs/data-sources/app.md
docs/data-sources/apps.md
docs/resources/app.md
internal/provider/datasource_app.go
internal/provider/datasource_apps.go
internal/provider/resource_app.go
internal/provider/types_app.go

- fix #84 
```bash
go test ./...
```
```
...
```
- ...

Changed buildpacks attribute to list from set for app

---

docs/resources/mta.md
examples/resources/cloudfoundry_mta/resource.tf
internal/provider/datasource_mtas_test.go
internal/provider/fixtures/resource_mta.yaml
internal/provider/fixtures/resource_mta_invalid_mta_path.yaml
internal/provider/fixtures/resource_mta_invalid_namespace.yaml
internal/provider/fixtures/resource_mta_url.yaml
internal/provider/resource_mta.go
internal/provider/resource_mta_test.go
internal/provider/types_mta.go

- fix #90 
```bash
go test ./...
```
```
...
```
- ...

Added blue-green deployment strategy for mta

---

internal/provider/resource_app.go

- fix #101 
```bash
go test ./...
```
```
...
```
- ...

Fix crash while updating app with rolling strategy

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/test.yml
docs/index.md
examples/provider/provider.tf

chore: Prep work for 1.2.0 release

---

docs/resources/space_role.md
examples/resources/cloudfoundry_space_role/import.sh

Closes: https://github.com/cloudfoundry/terraform-provider-cloudfoundry/issues/116
```bash
go test ./...
```
```
...
```
- ...

fix: Update for import document of space_role

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/test.yml
docs/index.md
examples/provider/provider.tf

- Release v1.3.0
- Release v1.3.0

chore: Prep Work

---

go.mod
go.sum
internal/provider/fixtures/resource_service_broker.yaml
internal/provider/fixtures/resource_service_broker_space.yaml
internal/provider/fixtures/resource_service_broker_space_invalid.yaml
internal/provider/types_org_quota.go
internal/provider/types_space_quota.go

- ref #91 
```bash
go test ./...
```
```
...
```
- ...

Add error details for failure in app resource

---

docs/resources/app.md
internal/provider/resource_app.go
internal/provider/resource_route.go
internal/provider/resource_route_test.go
internal/provider/types_route.go

- fix #126 
```bash
go test ./...
```
```
...
```
- ...

Fix bug in route resource when used with app

---

.devcontainer/default/devcontainer.json
.devcontainer/withenvfile/devcontainer.json
assets/install_cf.sh

- Install cf-cli during the build of the devcontainer
- Fixes #147 

feat: Add cf-cli

---

.github/workflows/test-opentofu.yml

- Update OpenTofu test matrix
- Align Test setup with Terraform test
- Closes #152 
```bash
go test ./...
```
n/a

test: update OpenTofu test matrix

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/test.yml
internal/provider/fixtures/datasource_service_plan.yaml
internal/provider/fixtures/datasource_service_plan_invalid.yaml
internal/provider/fixtures/provider.access_token.yaml
internal/provider/fixtures/provider.home_dir.yaml
internal/provider/fixtures/provider.user_pwd.yaml

- fix #150
```bash
go test ./...
```
```
...
```
- ...

Update terraform unit test matrix

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

chore: v1.4.0 Prep Work

---

docs/resources/user_cf.md
examples/resources/cloudfoundry_user_cf/import.sh

- Add import format for ```cloudfoundry_user_cf``` resource
```bash
go test ./...
```
```
...
```
- ...

Added comment for user_cf import

---

docs/data-sources/user.md
internal/provider/datasource_user.go

- Add note to user data source

chore: Add note

---

.github/workflows/test-opentofu.yml
.github/workflows/test.yml
.golangci.bck.yml
.golangci.yml
internal/mta/api_default.go
internal/mta/client.go
internal/provider/datasource_service_instance.go
internal/provider/utils_test.go

- Update the lint version from golangci-lint 1.x to 2.x
- Migrated the lint configuration from v1 to v2
- Fixed the static check errors coming after updating the linter version
```bash
go test ./...
```
```
...
```
- ...

Lint action update 

---

internal/provider/types_app.go

- fix #180 
```bash
go test ./...
```
```
...
```
- ...

fix : inconsistent plan for private docker app image

---

docs/resources/route.md
internal/provider/resource_route.go

- fix #182 
```bash
go test ./...
```
```
...
```
- ...

fix : route destination issue with app

---

docs/resources/mta.md
internal/mta/util.go
internal/provider/resource_mta.go

- fix #177 
```bash
go test ./...
```
```
...
```
- ...

feat: Added deploy logs for mta in TF_LOG

---

internal/provider/fixtures/resource_security_group_crud.yaml
internal/provider/fixtures/resource_security_group_invalid_name.yaml
internal/provider/fixtures/resource_security_group_invalid_rule.yaml
internal/provider/resource_security_group.go
internal/provider/resource_security_group_test.go
internal/provider/types_security_group.go

- fix #189 
```bash
go test ./...
```
```
...
```
- ...

fix : make spaces in security group computed so that overwrites dont happen

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

- Release prep v1.5.0
```bash
go test ./...
```
```
...
```
- ...

chore : v1.5.0 Prep Work

---

internal/provider/types_app.go

- fix #196 
```bash
go test ./...
```
```
...
```
- ...

fix : params instance binding in app

---

.github/workflows/set-default-pr-values.yaml

- GH Action to check the next open milestone and assign the PR
- Add the creator of the PR a the assignee
```bash
go test ./...
```
```
...
```

chore: GH Action - PR Default Milestone

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

- Update references to v1.6
```bash
go test ./...
```
```
...
```
- ...

chore: Prep v1.6

---

README.md

- Align badges of Terraform provider with other SAP supported providers (as far as possible).
```bash
go test ./...
```
na

chore: update badges to align with other SAP supported providers

---

.devcontainer/default/devcontainer.json
.devcontainer/withenvfile/devcontainer.json
.github/workflows/test-opentofu.yml

- Update OpenTofu version to latest release (1.10.0)
- Add OpenTofu feature to dev container
```bash
go test ./...
```
n/a

chore: update OpenTofu version to latest

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

Update version
```bash
go test ./...
```
```
...
```

chore: Prep v1.8

---

docs/index.md
docs/resources/service_instance.md
guides/DRIFTDETECTION.md
guides/IMPORT.md
templates/index.md.tmpl
templates/resources/service_instance.md.tmpl

- This PR adds markdown descrioptions as overviews about the import and drift detection capabilities for the different resource.
- It enhances the documentation in the registry concerning the overview as well as the details for the service instance pages.
- closes #113
```bash
go test ./...
```
n/a

docs: add information for import and drift detection

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
go.mod

- Update Go version to 1.25
- Cleanup of PR template
```bash
go test ./...
```
Release Notes: https://go.dev/doc/go1.25

chore(deps): Update Go version to 1.25

---

.github/ISSUE_TEMPLATE/bug_report.yml
docs/index.md
examples/provider/provider.tf

- update version
```bash
go test ./...
```

chore: Prep v1.9

---

.github/workflows/links-watcher-cron.yml

- Update workflow for link watcher to accept 429 codes due to changes in the Hashicorp documentation
- closes #303 
```bash
go test ./...
```
n/a

chore: update workflow for link watcher
